// Package nativemcp projects one mcporter inventory into the home fallback
// and the native Claude Code and Codex MCP registries.
package nativemcp

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

const (
	blockBegin = "# BEGIN agentic-os-kai mcporter-managed MCP servers"
	blockEnd   = "# END agentic-os-kai mcporter-managed MCP servers"
)

var legacyHeaderLines = []string{
	"# Generated by scripts/sync-codex-mcp.py from mcporter inventory.",
	"# Do not edit the managed block by hand.",
}

// Options names the canonical inventory, destination home, and check mode.
type Options struct {
	Inventory string
	Home      string
	Check     bool
}

// Result summarizes one projection without exposing endpoints or headers.
type Result struct {
	Servers int
	Changed bool
}

type server struct {
	Command string            `json:"command"`
	Args    []string          `json:"args"`
	Env     map[string]string `json:"env"`
	Cwd     string            `json:"cwd"`
	URL     string            `json:"url"`
	BaseURL string            `json:"baseUrl"`
	Headers map[string]string `json:"headers"`
	Codex   codexPolicy       `json:"x-codex"`
}

// codexPolicy carries projection metadata that mcporter and Claude ignore.
type codexPolicy struct {
	DefaultToolsApprovalMode string `json:"defaultToolsApprovalMode"`
}

type inventory struct {
	raw     []byte
	servers map[string]server
}

// Project converges the mcporter home file plus both native harness registries.
func Project(opts Options) (Result, error) {
	inv, err := loadInventory(opts.Inventory)
	if err != nil {
		return Result{}, err
	}
	home := strings.TrimSpace(opts.Home)
	if home == "" {
		home, err = os.UserHomeDir()
		if err != nil {
			return Result{}, fmt.Errorf("native MCP: resolve home: %w", err)
		}
	}

	claudePath := filepath.Join(home, ".claude.json")
	codexPath := filepath.Join(home, ".codex", "config.toml")
	mcporterPath := filepath.Join(home, ".mcporter", "mcporter.json")

	claudePayload, claudeChanged, err := renderClaude(claudePath, inv.servers, home)
	if err != nil {
		return Result{}, err
	}
	codexPayload, codexChanged, err := renderCodex(codexPath, inv.servers, home)
	if err != nil {
		return Result{}, err
	}
	mcporterChanged := !sameFile(mcporterPath, inv.raw)
	changed := mcporterChanged || claudeChanged || codexChanged
	result := Result{Servers: len(inv.servers), Changed: changed}
	if opts.Check || !changed {
		return result, nil
	}

	if mcporterChanged {
		if err := writeAtomic(mcporterPath, inv.raw, 0o600); err != nil {
			return Result{}, fmt.Errorf("native MCP: write mcporter home inventory: %w", err)
		}
	}
	if claudeChanged {
		if err := writeAtomic(claudePath, claudePayload, 0o600); err != nil {
			return Result{}, fmt.Errorf("native MCP: write Claude registry: %w", err)
		}
	}
	if codexChanged {
		if err := writeAtomic(codexPath, codexPayload, 0o600); err != nil {
			return Result{}, fmt.Errorf("native MCP: write Codex registry: %w", err)
		}
	}
	return result, nil
}

func loadInventory(path string) (inventory, error) {
	path = strings.TrimSpace(path)
	if path == "" {
		return inventory{}, fmt.Errorf("native MCP: inventory path is required")
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return inventory{}, fmt.Errorf("native MCP: read inventory: %w", err)
	}
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		return inventory{}, fmt.Errorf("native MCP: parse inventory: %w", err)
	}
	importsRaw, ok := top["imports"]
	if !ok {
		return inventory{}, fmt.Errorf("native MCP: inventory must set imports to []")
	}
	var imports []string
	if err := json.Unmarshal(importsRaw, &imports); err != nil || len(imports) != 0 {
		return inventory{}, fmt.Errorf("native MCP: inventory imports must be []")
	}
	var servers map[string]server
	if err := json.Unmarshal(top["mcpServers"], &servers); err != nil {
		return inventory{}, fmt.Errorf("native MCP: parse mcpServers: %w", err)
	}
	for name, cfg := range servers {
		if strings.TrimSpace(name) == "" {
			return inventory{}, fmt.Errorf("native MCP: server name must not be empty")
		}
		if cfg.endpoint() == "" && strings.TrimSpace(cfg.Command) == "" {
			return inventory{}, fmt.Errorf("native MCP: server %q has neither URL nor command", name)
		}
		mode := strings.TrimSpace(cfg.Codex.DefaultToolsApprovalMode)
		if !validCodexApprovalMode(mode) {
			return inventory{}, fmt.Errorf("native MCP: server %q has unsupported Codex approval mode %q", name, mode)
		}
		cfg.Codex.DefaultToolsApprovalMode = mode
		servers[name] = cfg
	}
	return inventory{raw: appendTrailingNewline(raw), servers: servers}, nil
}

func validCodexApprovalMode(mode string) bool {
	switch mode {
	case "", "auto", "prompt", "writes", "approve":
		return true
	default:
		return false
	}
}

func (s server) endpoint() string {
	if strings.TrimSpace(s.URL) != "" {
		return s.URL
	}
	return s.BaseURL
}

func renderClaude(path string, servers map[string]server, home string) ([]byte, bool, error) {
	top := map[string]json.RawMessage{}
	if raw, err := os.ReadFile(path); err == nil {
		if err := json.Unmarshal(raw, &top); err != nil {
			return nil, false, fmt.Errorf("native MCP: parse Claude config: %w", err)
		}
	} else if !os.IsNotExist(err) {
		return nil, false, fmt.Errorf("native MCP: read Claude config: %w", err)
	}

	desired := map[string]any{}
	for name, cfg := range servers {
		desired[name] = claudeServer(cfg, home)
	}
	mcpRaw, err := json.Marshal(desired)
	if err != nil {
		return nil, false, fmt.Errorf("native MCP: render Claude servers: %w", err)
	}
	var desiredComparable map[string]any
	if err := json.Unmarshal(mcpRaw, &desiredComparable); err != nil {
		return nil, false, fmt.Errorf("native MCP: normalize Claude servers: %w", err)
	}
	var current map[string]any
	if raw := top["mcpServers"]; len(raw) > 0 {
		_ = json.Unmarshal(raw, &current)
	}
	if reflect.DeepEqual(current, desiredComparable) {
		return nil, false, nil
	}
	top["mcpServers"] = mcpRaw
	payload, err := json.MarshalIndent(top, "", "  ")
	if err != nil {
		return nil, false, fmt.Errorf("native MCP: render Claude config: %w", err)
	}
	return appendTrailingNewline(payload), true, nil
}

func claudeServer(cfg server, home string) map[string]any {
	if endpoint := cfg.endpoint(); strings.TrimSpace(endpoint) != "" {
		out := map[string]any{
			"type": "http",
			"url":  expandHome(endpoint, home),
		}
		if len(cfg.Headers) > 0 {
			out["headers"] = expandMap(cfg.Headers, home)
		}
		return out
	}
	out := map[string]any{"command": expandHome(cfg.Command, home)}
	if len(cfg.Args) > 0 {
		out["args"] = expandSlice(cfg.Args, home)
	}
	if len(cfg.Env) > 0 {
		out["env"] = expandMap(cfg.Env, home)
	}
	if strings.TrimSpace(cfg.Cwd) != "" {
		out["cwd"] = expandHome(cfg.Cwd, home)
	}
	return out
}

func renderCodex(path string, servers map[string]server, home string) ([]byte, bool, error) {
	existing := ""
	if raw, err := os.ReadFile(path); err == nil {
		existing = string(raw)
	} else if !os.IsNotExist(err) {
		return nil, false, fmt.Errorf("native MCP: read Codex config: %w", err)
	}
	rendered := spliceManagedBlock(existing, codexBlock(servers, home))
	return []byte(rendered), rendered != existing, nil
}

func codexBlock(servers map[string]server, home string) string {
	var out strings.Builder
	out.WriteString(blockBegin + "\n")
	out.WriteString("# Generated by agent-compose from the canonical mcporter inventory.\n")
	out.WriteString("# Do not edit this managed block by hand.\n\n")
	names := sortedKeys(servers)
	for _, name := range names {
		cfg := servers[name]
		fmt.Fprintf(&out, "[mcp_servers.%s]\n", strconv.Quote(name))
		if endpoint := cfg.endpoint(); strings.TrimSpace(endpoint) != "" {
			fmt.Fprintf(&out, "url = %s\n", strconv.Quote(expandHome(endpoint, home)))
			if len(cfg.Headers) > 0 {
				fmt.Fprintf(&out, "http_headers = %s\n", tomlMap(expandMap(cfg.Headers, home)))
			}
		} else {
			fmt.Fprintf(&out, "command = %s\n", strconv.Quote(expandHome(cfg.Command, home)))
			if len(cfg.Args) > 0 {
				fmt.Fprintf(&out, "args = %s\n", tomlSlice(expandSlice(cfg.Args, home)))
			}
			if len(cfg.Env) > 0 {
				fmt.Fprintf(&out, "env = %s\n", tomlMap(expandMap(cfg.Env, home)))
			}
			if strings.TrimSpace(cfg.Cwd) != "" {
				fmt.Fprintf(&out, "cwd = %s\n", strconv.Quote(expandHome(cfg.Cwd, home)))
			}
		}
		if cfg.Codex.DefaultToolsApprovalMode != "" {
			fmt.Fprintf(&out, "default_tools_approval_mode = %s\n", strconv.Quote(cfg.Codex.DefaultToolsApprovalMode))
		}
		out.WriteString("\n")
	}
	out.WriteString(blockEnd + "\n")
	return out.String()
}

func spliceManagedBlock(existing, block string) string {
	existing = stripLegacyHeaders(existing)
	start := strings.Index(existing, blockBegin)
	end := strings.Index(existing, blockEnd)
	if start >= 0 && end >= start {
		end += len(blockEnd)
		rendered := existing[:start] + strings.TrimSuffix(block, "\n") + existing[end:]
		return strings.TrimSpace(rendered) + "\n"
	}
	if strings.TrimSpace(existing) == "" {
		return block
	}
	return strings.TrimSpace(existing) + "\n\n" + block
}

func stripLegacyHeaders(text string) string {
	lines := strings.Split(text, "\n")
	kept := lines[:0]
	for _, line := range lines {
		skip := false
		for _, legacy := range legacyHeaderLines {
			if line == legacy {
				skip = true
				break
			}
		}
		if !skip {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}

func tomlSlice(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func tomlMap(values map[string]string) string {
	keys := sortedKeys(values)
	items := make([]string, 0, len(keys))
	for _, key := range keys {
		items = append(items, strconv.Quote(key)+" = "+strconv.Quote(values[key]))
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func expandHome(value, home string) string {
	return strings.ReplaceAll(value, "${HOME}", home)
}

func expandSlice(values []string, home string) []string {
	out := make([]string, len(values))
	for i, value := range values {
		out[i] = expandHome(value, home)
	}
	return out
}

func expandMap(values map[string]string, home string) map[string]string {
	out := make(map[string]string, len(values))
	for key, value := range values {
		out[key] = expandHome(value, home)
	}
	return out
}

func sortedKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sameFile(path string, desired []byte) bool {
	current, err := os.ReadFile(path)
	return err == nil && bytes.Equal(current, desired)
}

func appendTrailingNewline(raw []byte) []byte {
	return append(bytes.TrimRight(raw, "\r\n"), '\n')
}

func writeAtomic(path string, payload []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".native-mcp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(payload); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if runtime.GOOS == "windows" {
		_ = os.Remove(path)
	}
	return os.Rename(tmpPath, path)
}
