// Package roster renders the seat dispatch table as a v1-cascade source:
// every agent self-selects its identity by harness and role at launch.
package roster

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"forgejo.coilysiren.me/coilyco-flight-deck/agent-compose/internal/person"
	"forgejo.coilysiren.me/coilyco-flight-deck/agent-compose/internal/schema"
)

// Render produces the artifact file set: the shared dispatch table, the
// claude override with mechanical imports, and the personality bodies found
// in the given sources. outDir only parameterizes the claude import paths.
func Render(p *person.Person, sources []*schema.Source, outDir string) (map[string][]byte, error) {
	files := map[string][]byte{}
	bodies := personalityBodies(p, sources)

	var table strings.Builder
	table.WriteString("<!-- generated by agent-compose roster; do not edit -->\n\n")
	table.WriteString("# Agent seats\n\n")
	table.WriteString("Each agent self-selects by harness and role: find your line and wear it\n")
	table.WriteString("for the whole session.\n")

	for _, roleName := range p.RoleOrder {
		role := p.Roles[roleName]
		if len(role.Seats) == 0 {
			continue
		}
		fmt.Fprintf(&table, "\n## %s - %s\n\n", roleName, role.Purpose)
		for _, seat := range role.Seats {
			fmt.Fprintf(&table, "- If you are %s running the %s role: your name is %s",
				seat.Harness, roleName, seat.Name)
			if seat.Pronouns != "" {
				fmt.Fprintf(&table, " (pronouns: %s)", seat.Pronouns)
			}
			table.WriteString(".\n")
		}
		table.WriteString("\n")
		table.WriteString(personalityLine(p, role, bodies))
		table.WriteString("\n")
	}
	files["AGENTS.COMPOSE.md"] = []byte(table.String())

	var imports []string
	for _, name := range sortedPersonalities(p) {
		if _, ok := bodies[name]; ok {
			imports = append(imports, fmt.Sprintf("@%s", filepath.Join(outDir, "personalities", name+".md")))
		}
	}
	if len(imports) > 0 {
		override := "## Personality definitions\n\n" +
			"Definitions load mechanically; read your role's line above to know\nwhich one is yours.\n\n" +
			strings.Join(imports, "\n") + "\n"
		files["AGENTS.claude.md"] = []byte(override)
	}

	for name, body := range bodies {
		files["personalities/"+name+".md"] = body
	}
	return files, nil
}

func personalityLine(p *person.Person, role person.Role, bodies map[string][]byte) string {
	if len(role.Personalities) == 0 {
		return "Compatible personalities: pending (#10).\n"
	}
	var parts []string
	for _, name := range role.Personalities {
		binding := p.Personalities[name]
		entry := name
		if binding.Color != "" {
			entry += " (favorite color " + binding.Color + ")"
		}
		if _, ok := bodies[name]; ok {
			entry += ", defined in [" + name + "](personalities/" + name + ".md)"
		} else {
			entry += ", definition pending"
		}
		parts = append(parts, entry)
	}
	return "Compatible personalities: " + strings.Join(parts, "; ") + ".\n"
}

// personalityBodies pulls each bound skill's SKILL.md from the first source
// that provides it; absent bodies degrade to pending markers in the table.
func personalityBodies(p *person.Person, sources []*schema.Source) map[string][]byte {
	bodies := map[string][]byte{}
	for name, binding := range p.Personalities {
		for _, src := range sources {
			for _, skill := range src.Skills {
				if skill.ID != binding.Skill {
					continue
				}
				raw, err := os.ReadFile(filepath.Join(src.Root, skill.Path, "SKILL.md"))
				if err == nil {
					bodies[name] = raw
				}
				break
			}
			if _, ok := bodies[name]; ok {
				break
			}
		}
	}
	return bodies
}

func sortedPersonalities(p *person.Person) []string {
	names := make([]string, 0, len(p.Personalities))
	for name := range p.Personalities {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
