// Package roster renders the seat dispatch table as a v1-cascade source:
// every agent self-selects its identity by harness and role at launch.
package roster

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"forgejo.coilysiren.me/coilyco-flight-deck/agent-compose/internal/color"
	"forgejo.coilysiren.me/coilyco-flight-deck/agent-compose/internal/person"
	"forgejo.coilysiren.me/coilyco-flight-deck/agent-compose/internal/schema"
)

// Render produces the artifact file set; outDir only parameterizes the
// absolute paths inside the claude override's mechanical imports.
func Render(p *person.Person, sources []*schema.Source, outDir string) (map[string][]byte, error) {
	personSource, err := person.Source(p)
	if err != nil {
		return nil, err
	}
	sources = append([]*schema.Source{personSource}, sources...)

	files := map[string][]byte{}
	bodies := personalityBodies(p, sources)
	instructions, err := instructionBodies(sources)
	if err != nil {
		return nil, err
	}

	var table strings.Builder
	table.WriteString("<!-- generated by agent-compose roster; do not edit -->\n\n")
	for _, body := range instructions {
		table.Write(body)
		if len(body) > 0 && body[len(body)-1] != '\n' {
			table.WriteString("\n")
		}
		table.WriteString("\n")
	}
	table.WriteString("# Agent seats\n\n")
	table.WriteString("Each agent resolves its role once at session start. If launch context assigns\n")
	table.WriteString("a role, the agent treats that assignment as authoritative. Otherwise, an\n")
	table.WriteString("unassigned native agent uses the initial substantive request as a soft signal\n")
	table.WriteString("and selects the closest role. The agent keeps that role for the whole session.\n")
	table.WriteString("Later task shape does not change it.\n")
	table.WriteString("Each agent loads every linked definition on that role's Melded personalities\n")
	table.WriteString("line before acting. Definitions on other roles stay inactive.\n")

	for _, roleName := range p.RoleOrder {
		role := p.Roles[roleName]
		if len(role.Seats) == 0 {
			continue
		}
		fmt.Fprintf(&table, "\n## %s - %s\n\n", roleName, role.Purpose)
		table.WriteString(role.Briefing)
		table.WriteString("\n\n")
		for _, seat := range role.Seats {
			fmt.Fprintf(&table, "- If you are %s running the %s role: your name is %s",
				seat.Harness, roleName, seat.Name)
			if seat.Pronouns != "" {
				fmt.Fprintf(&table, " (pronouns: %s)", seat.Pronouns)
			}
			table.WriteString(".\n")
		}
		table.WriteString("\n")
		line, err := personalityLine(p, role, bodies)
		if err != nil {
			return nil, fmt.Errorf("render role %q: %w", roleName, err)
		}
		table.WriteString(line)
		table.WriteString("\n")
	}
	files["AGENTS.COMPOSE.md"] = []byte(table.String())

	var imports []string
	for _, name := range sortedPersonalities(p) {
		if _, ok := bodies[name]; ok {
			imports = append(imports, fmt.Sprintf("@%s", filepath.Join(outDir, "personalities", name+".md")))
		}
	}
	if len(imports) > 0 {
		override := "## Personality definitions\n\n" +
			"Definitions load mechanically; read your role's line above to know\nwhich ones are yours.\n\n" +
			strings.Join(imports, "\n") + "\n"
		files["AGENTS.claude.md"] = []byte(override)
	}

	for name, body := range bodies {
		files["personalities/"+name+".md"] = body
	}
	return files, nil
}

// instructionBodies preserves source order and rejects divergent copies of a
// shared instruction, matching bundle resolution at the host roster boundary.
func instructionBodies(sources []*schema.Source) ([][]byte, error) {
	selected := map[string][]byte{}
	var bodies [][]byte
	for _, src := range sources {
		for _, instruction := range src.Instructions {
			raw, err := src.ReadFile(instruction.Path)
			if err != nil {
				return nil, fmt.Errorf("source %q instruction %q: %w", src.ID, instruction.ID, err)
			}
			if prior, ok := selected[instruction.ID]; ok {
				if bytes.Equal(prior, raw) {
					continue
				}
				return nil, fmt.Errorf("instruction %q has conflicting roster source copies", instruction.ID)
			}
			selected[instruction.ID] = raw
			bodies = append(bodies, raw)
		}
	}
	return bodies, nil
}

func personalityLine(p *person.Person, role person.Role, bodies map[string][]byte) (string, error) {
	if len(role.Personalities) == 0 {
		return "Melded personalities: pending (#10).\n", nil
	}
	var parts []string
	var colors []string
	for _, name := range role.Personalities {
		binding := p.Personalities[name]
		colors = append(colors, binding.Color)
		entry := name
		if binding.Color != "" {
			entry += " (favorite color " + binding.Color + ")"
		}
		if _, ok := bodies[name]; ok {
			entry += ", defined in [" + name + "](personalities/" + name + ".md)"
		} else {
			entry += ", definition pending"
		}
		parts = append(parts, entry)
	}
	favorite, err := color.Favorite(colors)
	if err != nil {
		return "", err
	}
	return "Melded personalities: " + strings.Join(parts, "; ") +
		". Melded favorite color: " + favorite + ".\n", nil
}

// personalityBodies pulls each bound skill's SKILL.md from the first source
// that provides it; absent bodies degrade to pending markers in the table.
func personalityBodies(p *person.Person, sources []*schema.Source) map[string][]byte {
	bodies := map[string][]byte{}
	for name, binding := range p.Personalities {
		for _, src := range sources {
			for _, skill := range src.Skills {
				if skill.ID != binding.Skill {
					continue
				}
				raw, err := src.ReadFile(filepath.ToSlash(filepath.Join(skill.Path, "SKILL.md")))
				if err == nil {
					bodies[name] = raw
				}
				break
			}
			if _, ok := bodies[name]; ok {
				break
			}
		}
	}
	return bodies
}

func sortedPersonalities(p *person.Person) []string {
	names := make([]string, 0, len(p.Personalities))
	for name := range p.Personalities {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
