// Package cascade is the absorbed v1 composer: it composes AGENTS.COMPOSE.md
// doctrine sources into COMPOSED files, wires harness load-point symlinks,
// and emits the compiled repository plan convergence consumers read.
package cascade

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"forgejo.coilysiren.me/coilyco-flight-deck/agent-compose/internal/personpolicy"
)

const (
	Banner         = "<!-- generated by agent-compose from agent-compose.yaml; do not edit -->"
	manifestBanner = "generated by agent-compose from agent-compose.yaml; do not edit"
	sourceFilename = "AGENTS.COMPOSE.md"
)

type Config struct {
	Scopes               *scopeList          `yaml:"scopes"`
	Sources              []string            `yaml:"sources"`
	Roots                []string            `yaml:"roots"`
	LoadPoints           map[string]RawValue `yaml:"load_points"`
	PersonPolicy         string              `yaml:"person_policy"`
	PersonSource         string              `yaml:"person_source"`
	PersonalityLibraries []string            `yaml:"personality_libraries"`
	RosterSources        []string            `yaml:"roster_sources"`
	SkillLoadPoints      map[string]RawValue `yaml:"skill_load_points"`
	SkillCatalogManifest string              `yaml:"skill_catalog_manifest"`
	OperatingContext     []string            `yaml:"operating_context"`
}

// scopeList accepts a scalar or a sequence, mirroring v1's normalizer; its
// presence (not emptiness) is what turns scope filtering on.
type scopeList []string

func (s *scopeList) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind == yaml.ScalarNode {
		*s = scopeList{node.Value}
		return nil
	}
	var values []string
	if err := node.Decode(&values); err != nil {
		return err
	}
	*s = values
	return nil
}

// RawValue keeps a load-point value's truthiness: null and false opt a
// harness out, a non-empty string sets its path.
type RawValue struct {
	node yaml.Node
}

func (r *RawValue) UnmarshalYAML(node *yaml.Node) error {
	r.node = *node
	return nil
}

func (r RawValue) truthy() bool {
	switch r.node.Tag {
	case "!!null":
		return false
	case "!!bool":
		return r.node.Value == "true"
	default:
		return r.node.Value != ""
	}
}

func LoadConfig(path string) (*Config, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := decodeStrictYAML(raw, path, &cfg); err != nil {
		return nil, err
	}
	if err := personpolicy.Validate(cfg.PersonPolicy, cfg.PersonSource); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	seenRepositories := map[string]bool{}
	for _, repository := range cfg.OperatingContext {
		if err := validateConfiguredRepository(repository); err != nil {
			return nil, fmt.Errorf("%s: operating_context: %w", path, err)
		}
		if seenRepositories[repository] {
			return nil, fmt.Errorf("%s: operating_context repeats %q", path, repository)
		}
		seenRepositories[repository] = true
	}
	return &cfg, nil
}

func validateConfiguredRepository(value string) error {
	if value == "" || strings.Contains(value, `\`) || filepath.IsAbs(value) || filepath.Clean(value) != value {
		return fmt.Errorf("repository %q must be a clean owner/repository path", value)
	}
	parts := strings.Split(filepath.ToSlash(value), "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return fmt.Errorf("repository %q must have owner/repository form", value)
	}
	return nil
}

func decodeStrictYAML(raw []byte, path string, value any) error {
	decoder := yaml.NewDecoder(bytes.NewReader(raw))
	decoder.KnownFields(true)
	if err := decoder.Decode(value); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return fmt.Errorf("%s: trailing YAML document", path)
	}
	return nil
}

func expand(path string) string {
	if path == "~" || strings.HasPrefix(path, "~/") {
		home, err := os.UserHomeDir()
		if err == nil {
			return filepath.Join(home, strings.TrimPrefix(strings.TrimPrefix(path, "~"), "/"))
		}
	}
	return path
}

// ResolveConfiguredPath expands one host-config path against its config file
// and injectable home directory.
func ResolveConfiguredPath(value, configPath, home string) string {
	value = strings.TrimSpace(value)
	if value == "~" || strings.HasPrefix(value, "~/") {
		return filepath.Join(home, strings.TrimPrefix(strings.TrimPrefix(value, "~"), "/"))
	}
	if filepath.IsAbs(value) {
		return value
	}
	return filepath.Join(filepath.Dir(configPath), value)
}

// DefaultLoadPoints wires claude and codex; opencode stays opt-in via config.
func DefaultLoadPoints() map[string]string {
	home, err := os.UserHomeDir()
	if err != nil {
		return map[string]string{}
	}
	return map[string]string{
		"claude": filepath.Join(home, ".claude", "CLAUDE.md"),
		"codex":  filepath.Join(home, ".codex", "AGENTS.md"),
	}
}

// ResolveLoadPoints merges config overrides over the defaults; falsy values
// (null, false, empty) opt a harness out entirely.
func ResolveLoadPoints(cfg *Config) map[string]string {
	return resolvePoints(DefaultLoadPoints(), cfg.LoadPoints)
}

// DefaultSkillLoadPoints mirrors DefaultLoadPoints for skills. Claude reads only
// `.claude/skills`, never the portable directory; see docs/projection.md.
func DefaultSkillLoadPoints() map[string]string {
	home, err := os.UserHomeDir()
	if err != nil {
		return map[string]string{}
	}
	return map[string]string{
		"claude": filepath.Join(home, ".claude", "skills"),
		"codex":  filepath.Join(home, ".agents", "skills"),
	}
}

// ResolveSkillLoadPoints merges config overrides over the skill defaults, with
// the same falsy opt-out as ResolveLoadPoints.
func ResolveSkillLoadPoints(cfg *Config) map[string]string {
	return resolvePoints(DefaultSkillLoadPoints(), cfg.SkillLoadPoints)
}

func resolvePoints(points map[string]string, overrides map[string]RawValue) map[string]string {
	for harness, value := range overrides {
		if value.truthy() {
			points[harness] = expand(value.node.Value)
		} else {
			delete(points, harness)
		}
	}
	return points
}

// splitFrontmatter separates a leading `--- ... ---` YAML block from the
// body; malformed fences or YAML degrade to no metadata, as in v1.
func splitFrontmatter(text string) (map[string]any, string) {
	lines := strings.Split(text, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return map[string]any{}, text
	}
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != "---" {
			continue
		}
		var meta map[string]any
		if err := yaml.Unmarshal([]byte(strings.Join(lines[1:i], "\n")), &meta); err != nil || meta == nil {
			meta = map[string]any{}
		}
		return meta, strings.Join(lines[i+1:], "\n")
	}
	return map[string]any{}, text
}

func normalizeScopes(value any) []string {
	switch v := value.(type) {
	case string:
		return []string{v}
	case []any:
		out := make([]string, 0, len(v))
		for _, item := range v {
			out = append(out, fmt.Sprint(item))
		}
		return out
	default:
		return nil
	}
}

// parseSource returns a source's declared scopes and frontmatter-stripped body.
func parseSource(path string) ([]string, string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, "", err
	}
	meta, body := splitFrontmatter(string(raw))
	return normalizeScopes(meta["scopes"]), body, nil
}

func sourceHarnesses(path string) ([]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	meta, _ := splitFrontmatter(string(raw))
	return normalizeScopes(meta["harnesses"]), nil
}

// discoverSources finds AGENTS.COMPOSE.md under root, skipping dot-dirs,
// sorted for determinism.
func discoverSources(root string) ([]string, error) {
	var found []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && strings.HasPrefix(d.Name(), ".") && p != root {
			return filepath.SkipDir
		}
		if !d.IsDir() && d.Name() == sourceFilename {
			found = append(found, p)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(found)
	return found, nil
}

// GatherSources resolves explicit entries in listed order, then discovered
// root entries sorted; duplicates collapse to first occurrence.
func GatherSources(cfg *Config) ([]string, []string) {
	var errors []string
	var ordered []string
	seen := map[string]bool{}
	add := func(path string) {
		key, err := filepath.Abs(path)
		if err != nil {
			key = path
		}
		if !seen[key] {
			seen[key] = true
			ordered = append(ordered, path)
		}
	}
	for _, raw := range cfg.Sources {
		src := expand(raw)
		if info, err := os.Stat(src); err != nil || info.IsDir() {
			errors = append(errors, fmt.Sprintf("source not found: %s", src))
			continue
		}
		add(src)
	}
	for _, raw := range cfg.Roots {
		root := expand(raw)
		if info, err := os.Stat(root); err != nil || !info.IsDir() {
			errors = append(errors, fmt.Sprintf("root is not a directory: %s", root))
			continue
		}
		found, err := discoverSources(root)
		if err != nil {
			errors = append(errors, fmt.Sprintf("walk %s: %v", root, err))
			continue
		}
		for _, src := range found {
			add(src)
		}
	}
	return ordered, errors
}

// SelectByScope keeps sources whose scopes intersect the machine's; nil
// machine scopes disables filtering, and untagged sources drop under it.
func SelectByScope(sources []string, machineScopes []string, filtering bool) []string {
	if !filtering {
		return sources
	}
	wanted := map[string]bool{}
	for _, s := range machineScopes {
		wanted[s] = true
	}
	var kept []string
	for _, path := range sources {
		scopes, _, err := parseSource(path)
		if err != nil {
			continue
		}
		for _, s := range scopes {
			if wanted[s] {
				kept = append(kept, path)
				break
			}
		}
	}
	return kept
}

func selectByHarness(sources []string, harness string) []string {
	var kept []string
	for _, path := range sources {
		allowed, err := sourceHarnesses(path)
		if err != nil {
			continue
		}
		if allowed == nil || contains(allowed, harness) {
			kept = append(kept, path)
		}
	}
	return kept
}

// discoverOverride finds the sibling AGENTS.<harness>.md beside a base
// source; the directory binds it, so it can only patch that base.
func discoverOverride(base, harness string) string {
	candidate := filepath.Join(filepath.Dir(base), "AGENTS."+harness+".md")
	if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
		return candidate
	}
	return ""
}

func contains(list []string, item string) bool {
	for _, entry := range list {
		if entry == item {
			return true
		}
	}
	return false
}
