package palette

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/coilyco-flight-deck/agent-compose/v2/internal/color"
	"github.com/coilyco-flight-deck/agent-compose/v2/internal/person"
)

// SnapshotPath is the committed record of the derived role palette, relative
// to the repository root.
const SnapshotPath = "internal/palette/role-palette.txt"

// RenderSnapshot writes the derived role colors, so a roster edit arrives as a
// reviewable diff rather than silent drift across every rendered surface.
func RenderSnapshot(p *person.Person) ([]byte, error) {
	if p == nil {
		return nil, fmt.Errorf("render role palette: person is nil")
	}
	favorites := make([]string, 0, len(p.RoleOrder))
	for _, name := range p.RoleOrder {
		favorites = append(favorites, p.Roles[name].FavoriteColor)
	}
	separation, err := color.MinSeparation(favorites)
	if err != nil {
		return nil, fmt.Errorf("render role palette: %w", err)
	}
	backgrounds := make([]string, 0, len(p.RoleOrder))
	for _, name := range p.RoleOrder {
		backgrounds = append(backgrounds, p.Roles[name].Background)
	}
	backgroundSeparation, err := color.MinSeparation(backgrounds)
	if err != nil {
		return nil, fmt.Errorf("render role palette: %w", err)
	}

	var out bytes.Buffer
	out.WriteString("Generated by `agent-compose palette-snapshot`. Do not edit.\n\n")
	out.WriteString("Each role's favorite color is derived from the whole roster at once, not\n")
	out.WriteString("from its own personalities alone. Roles that share personalities have\n")
	out.WriteString("nearly identical component means, so a per-role average cannot tell them\n")
	out.WriteString("apart.\n\n")
	out.WriteString("Two stages. Each role first blends its components weighted by how few other\n")
	out.WriteString("roles share them, so whatever distinguishes a role leads its color. Then\n")
	out.WriteString("every role is pushed away from its nearest neighbor to grow the smallest\n")
	out.WriteString("pairwise distance, bounded by a drift cap so no color leaves its own blend,\n")
	out.WriteString("and clamped back into the terminal-legible band. Iteration order is fixed\n")
	out.WriteString("and nothing is random, so one roster always derives one palette.\n\n")
	out.WriteString("Roster loading asserts a floor on the closest pair. Two roles melding the\n")
	out.WriteString("same personalities derive barely 0.06 apart and fail it.\n\n")
	out.WriteString("The derivation is global, so editing one role can move every color below.\n")
	out.WriteString("That is why this file is committed: the change arrives as a diff.\n\n")
	out.WriteString("The window background is a second derivation from the same set. Accents\n")
	out.WriteString("live in the legible band, so tinting one into a near-black leaves seven\n")
	out.WriteString("backgrounds nobody can tell apart. Each role's hue is held and moved onto\n")
	out.WriteString("equal spacing at a fixed low lightness and chroma, at the rotation offset\n")
	out.WriteString("that turns every role the least. agentic-os#1245, #358.\n\n")
	fmt.Fprintf(&out, "Closest accent pair: %.4f\n", separation)
	fmt.Fprintf(&out, "Closest background pair: %.4f\n\n", backgroundSeparation)
	for _, name := range p.RoleOrder {
		role := p.Roles[name]
		fmt.Fprintf(
			&out,
			"%s // %s // %s // %s\n",
			name,
			role.FavoriteColor,
			role.Background,
			strings.Join(role.Personalities, ", "),
		)
	}
	return out.Bytes(), nil
}

// CheckSnapshot reports whether the committed page still matches the roster.
func CheckSnapshot(path string, rendered []byte) error {
	committed, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if !bytes.Equal(committed, rendered) {
		return fmt.Errorf(
			"%s is stale: run `agent-compose palette-snapshot` and stage the result",
			path,
		)
	}
	return nil
}

// WriteSnapshot replaces the committed page.
func WriteSnapshot(path string, rendered []byte) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, rendered, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
